# Generated by Django 5.2 on 2025-11-12 23:34

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RemoveConstraint(
            model_name='program',
            name='unique_program_per_client_day',
        ),
        migrations.AddField(
            model_name='program',
            name='time',
            field=models.TimeField(db_index=True, default=datetime.time(9, 0)),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('client', 'date', 'time')},
        ),
    ]
