# Generated by Django 5.2 on 2025-11-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_program_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['date', 'time', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='program',
            name='time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
    ]
