# Generated by Django 5.2 on 2025-11-13 00:50

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_program_options_alter_program_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='time',
            field=models.TimeField(db_index=True, default=datetime.time(9, 0)),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['client', 'date'], name='api_program_client__c15dac_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['client', 'date', 'time'], name='api_program_client__6e14d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('client', 'date', 'time'), name='uniq_program_per_client_day_time'),
        ),
    ]
