# Generated by Django 5.2 on 2025-11-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_program_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RemoveConstraint(
            model_name='program',
            name='uniq_program_per_client_day_time',
        ),
        migrations.AlterField(
            model_name='program',
            name='time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
    ]
