# Generated by Django 5.2 on 2025-11-13 02:05

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_program_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['date', 'time', 'id']},
        ),
        migrations.AlterField(
            model_name='program',
            name='time',
            field=models.TimeField(db_index=True, default=datetime.time(9, 0)),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('client', 'date', 'time'), name='uniq_program_per_client_day_time'),
        ),
    ]
